### ISSUE TITLE
Not indexing version object correctly

### ISSUE THREAD

**Issue by unional** [typings/api#63]
```js
    "4.0.0": [
      "github:typed-typings/env-node/4#a36ce8a19f93da8798bf06e11ee34fd823e0b185",
      {
        "compiler": "1.9.0",
        "description": "For TypeScript 1.9",
        "location": "github:typed-typings/env-node/4#10050df9e714121f730974cbaa7919215e158fa0"
      }
    ]
```

https://github.com/typings/registry/blob/master/env/node.json#L9-L13

https://github.com/typed-typings/env-node/issues/10#issuecomment-221961978

Feel free to improve the title. :smirk:

**Comment by blakeembrey** [comment]
Sorry that took a while for me to get back around to. It's working now: http://api.typings.org/entries/env/node/versions.

**Comment by unional** [comment]
No problem. :smile: I was referencing it directly.
